#!/usr/bin/env bash
# scripts/build.sh <dev|release> [--upload <port>] [--keep-apps]
#
# Builds the firmware (docs/os/guides/build-flash-provision.md, "Build profiles" and "Build
# directory"). In order:
#   1. writes src/vk/vk_profile.h for the profile (VK_PROFILE_DEV 1 or 0);
#   2. runs scripts/preflash-check.sh <profile>; a failed check stops the build;
#   3. arduino-cli compile, sketch path = this folder, --build-path build/<profile>
#      (one build directory per profile, so builds are incremental and a release upload can
#      never send a dev image);
#   4. prints the image size;
#   5. with --upload <port>: arduino-cli upload from the same build directory, at 460800 baud, then
#      the apps: an image of the filesystem partition with every app of the profile, so a flashed
#      badge shows its apps and folders at once. That replaces the filesystem: history, contacts and
#      consents start empty; the key and the settings (NVS) are kept. --keep-apps flashes only the
#      firmware and leaves the filesystem as it is.
#
# Works from any directory and with a space in the repository path.

set -euo pipefail

FQBN="esp32:esp32:esp32s3:PSRAM=opi,FlashSize=16M,PartitionScheme=custom,CDCOnBoot=cdc"
UPLOAD_FQBN="$FQBN,UploadSpeed=460800"   # the default 921600 fails on the badge's CH340

usage() {
  echo "usage: scripts/build.sh <dev|release> [--upload <port>] [--keep-apps]" >&2
  exit 2
}

FW="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

PROFILE="${1:-}"
case "$PROFILE" in
  dev) PROFILE_DEV=1 ;;
  release) PROFILE_DEV=0 ;;
  *) usage ;;
esac
shift

UPLOAD_PORT=""
KEEP_APPS=0
while [ $# -gt 0 ]; do
  case "$1" in
    --upload)
      [ $# -ge 2 ] || usage
      UPLOAD_PORT="$2"
      shift 2
      ;;
    --keep-apps) KEEP_APPS=1; shift ;;
    *) usage ;;
  esac
done

command -v arduino-cli > /dev/null || { echo "[build] arduino-cli is not on the PATH" >&2; exit 1; }

BUILD="$FW/build/$PROFILE"
LOG="$FW/build/$PROFILE-compile.log"
PROFILE_H="$FW/src/vk/vk_profile.h"

# 1. The profile header. Rewritten only when its content changes, so an unchanged profile does
#    not force a recompile of everything that includes vk_build.h.
WANTED="// Generated by scripts/build.sh ($PROFILE profile). Do not edit; not committed.
#pragma once
#define VK_PROFILE_DEV $PROFILE_DEV"
if [ ! -f "$PROFILE_H" ] || [ "$(cat "$PROFILE_H")" != "$WANTED" ]; then
  printf '%s\n' "$WANTED" > "$PROFILE_H"
  echo "[build] wrote src/vk/vk_profile.h (VK_PROFILE_DEV $PROFILE_DEV)"
fi

# 2. Pre-flash checks.
"$FW/scripts/preflash-check.sh" "$PROFILE"

# 3. Compile.
mkdir -p "$BUILD"
echo "[build] compiling the $PROFILE profile into build/$PROFILE"
arduino-cli compile --fqbn "$FQBN" --build-path "$BUILD" "$FW" 2>&1 | tee "$LOG"

# 4. Image size: arduino-cli's own summary line, and the size of the application image file.
SIZE_LINE="$(grep -E '^Sketch uses [0-9]+ bytes' "$LOG" | tail -n 1 || true)"
if [ -n "$SIZE_LINE" ]; then
  echo "[build] image ($PROFILE): $SIZE_LINE"
fi
if [ -f "$BUILD/os.ino.bin" ]; then
  echo "[build] build/$PROFILE/os.ino.bin: $(wc -c < "$BUILD/os.ino.bin" | tr -d ' ') bytes"
fi

# 5. Upload the image that was just built.
if [ -n "$UPLOAD_PORT" ]; then
  echo "[build] uploading the $PROFILE profile to $UPLOAD_PORT"
  arduino-cli upload --fqbn "$UPLOAD_FQBN" --build-path "$BUILD" -p "$UPLOAD_PORT" "$FW" || exit 1
  if [ "$KEEP_APPS" -eq 0 ]; then
    offset="$(awk -F, '$1 ~ /^spiffs/ {gsub(/ /, "", $4); print $4}' "$FW/partitions.csv")"
    echo "[build] flashing the $PROFILE apps at $offset (history, contacts and consents start empty)"
    "$FW/scripts/push-apps.sh" --image "$BUILD/apps.bin" "$PROFILE" || exit 1
    PY="${VK_PYTHON:-$FW/../.venv/bin/python}"
    "$PY" -m esptool --chip esp32s3 --port "$UPLOAD_PORT" --baud 460800 write_flash "$offset" "$BUILD/apps.bin" || exit 1
  fi
fi
