// src/vk/vk_build.h
// Compile-time switches (architecture/overview.md, section 10). Preprocessor only: this file is
// included from C and C++ and from upstream's buttons.cpp (hook H17).
// These are the only build-time choices; everything else is provisioned config.
#pragma once

#ifdef VK_HOST_TEST
#define VK_PROFILE_DEV 1
#else
#if defined(__has_include)
#if !__has_include("vk_profile.h")
#error "src/vk/vk_profile.h is missing: build with scripts/build.sh <dev|release>, which generates it"
#endif
#endif
#include "vk_profile.h"   // generated by scripts/build.sh: defines VK_PROFILE_DEV as 1 (dev) or 0 (release)
#endif

#ifndef VK_PROFILE_DEV
#error "VK_PROFILE_DEV is not defined: src/vk/vk_profile.h must define it as 1 or 0"
#endif

// SELECT allowed on some red screens, with a permanent "DEV BUILD" banner (wallet/approval.md, Dev builds).
#define VK_DEV_ALLOW_UNVERIFIED VK_PROFILE_DEV

// Compiles features/devtools/ (screen dump, button injection).
#define VK_TEST_HOOKS VK_PROFILE_DEV

// 0 = TweetNaCl (upstream), 1 = Monocypher (wallet/signing.md, Crypto backend).
#define VK_ED25519_BACKEND 0

// 1 = never use the SE050 for the key (wallet/signing.md, Key). Needs hook H18.
#define VK_FORCE_SOFTWARE_KEY 0

// 1 = never address the SE050 on the I2C bus: se050::test(), se050_t1::begin() and badge_i2c::scan() return at once
// (upstream-hooks.md, H21; finding F17). Set to 0 only on a badge whose SE050 is known to work.
#define VK_SE050_QUARANTINE 1

// Reported to apps as badge.api_version. Bump together with hook H16.
#define VK_API_VERSION 2
