import test from 'node:test';
import assert from 'node:assert/strict';
import { createPublicKey, verify } from 'node:crypto';
import { createKeyPairSignerFromPrivateKeyBytes, getAddressEncoder } from '@solana/kit';
import { canonicalRecord, compactRecord, signRecord, buildSignedRecord, getSignedRecord } from './records.js';

// Reference record from badge-os os/test/host/vectors.json (vk.record), generated by vectors.mjs. TEST KEYS ONLY:
// the seeds are SHA-256 of fixed labels. The badge's parser is tested against these same bytes.
const V = {
  issuerSeed: 'ace8afcbd62ec568431f11cbfce31405f1c550c0c206b3afc4f542bd014ead99',
  issuerPub: '3J8giwuzrAgnuusHwtKN3Ha65U979J2gnZUn8xUsyvnk',
  text: 'v=1\nattestation=GpKipmyKAyJYMdymUMbhjXX91rDxrLENh6YTY64UuPQg\ndisplay_name=MHacks Merch\n'
    + 'device_pubkey=2cd3e806c69ed2ca678a382228c10b3faa48850a7de06dd799bd7d2463ab76fd\nkind=merchant\n'
    + 'solana_wallet=ea67df107eddb995d02c641549ff5dd48158ea41ef40bc3738ac3bdd0eb5bdca\n'
    + 'solana_ata=178d80b67636ac4539a4c92fb3285cb17684ef97a9bdb5c354bf16b5f4e22b5b\n'
    + 'bank_ref_hash=\nexpiry=1800000000\nstatus=active\nissued_at=1790000000',
  sig: '8196daede05ecaeb4a762152efab9f0eba3fe08f00d156ff9cac4930ce6a8fceb39e0ebf8d19eddf31d9d91a85981fe1ca74d4f0c23473326ae7ca5a10299e0f',
};
const h = s => Buffer.from(s, 'hex');
const FIELDS = {
  attestation: 'GpKipmyKAyJYMdymUMbhjXX91rDxrLENh6YTY64UuPQg', display_name: 'MHacks Merch',
  device_pubkey: h('2cd3e806c69ed2ca678a382228c10b3faa48850a7de06dd799bd7d2463ab76fd'), kind: 'merchant',
  solana_wallet: h('ea67df107eddb995d02c641549ff5dd48158ea41ef40bc3738ac3bdd0eb5bdca'),
  solana_ata: h('178d80b67636ac4539a4c92fb3285cb17684ef97a9bdb5c354bf16b5f4e22b5b'),
  bank_ref_hash: null, expiry: 1800000000, status: 'active', issued_at: 1790000000,
};
const issuer = () => createKeyPairSignerFromPrivateKeyBytes(h(V.issuerSeed));
const ed25519Ok = (signer, msg, sig) => verify(null, msg, createPublicKey({ format: 'jwk',
  key: { kty: 'OKP', crv: 'Ed25519', x: Buffer.from(getAddressEncoder().encode(signer.address)).toString('base64url') } }), sig);

test('canonicalRecord reproduces the badge-os reference record byte for byte', () => {
  assert.equal(canonicalRecord(FIELDS).toString('utf8'), V.text);
});

test('signRecord over registry: matches the reference signature and verifies with node:crypto', async () => {
  const s = await issuer();
  assert.equal(s.address, V.issuerPub);
  const sig = await signRecord(s, canonicalRecord(FIELDS), 'registry:');
  assert.equal(sig.toString('hex'), V.sig);
  assert.ok(ed25519Ok(s, Buffer.concat([Buffer.from('registry:'), Buffer.from(V.text)]), sig));
  assert.ok(!ed25519Ok(s, Buffer.from(V.text), sig), 'must not verify without the prefix');
});

test('revoked, issuer-only fallback and empty optional fields', () => {
  const t = canonicalRecord({ ...FIELDS, attestation: null, status: 'revoked', solana_wallet: null, solana_ata: null,
    bank_ref_hash: Buffer.alloc(32, 0xab), kind: 'relay', expiry: 0 }).toString();
  assert.match(t, /^v=1\nattestation=none\n/);
  assert.match(t, /\nkind=relay\nsolana_wallet=\nsolana_ata=\nbank_ref_hash=(ab){32}\nexpiry=0\nstatus=revoked\nissued_at=1790000000$/);
  assert.ok(!t.endsWith('\n'));
});

test('canonicalRecord refuses what the badge parser would reject', () => {
  for (const bad of [{ display_name: '' }, { display_name: 'x'.repeat(33) }, { display_name: 'café' }, { kind: 'bank' },
                     { status: 'expired' }, { device_pubkey: Buffer.alloc(31) }, { solana_ata: Buffer.alloc(33) }, { expiry: -1 }])
    assert.throws(() => canonicalRecord({ ...FIELDS, ...bad }), /registry record/);
});

test('compactRecord follows 00 §9.3 offsets and lengths', () => {
  const b = compactRecord(FIELDS);
  assert.equal(b.length, 140 + 'MHacks Merch'.length);
  assert.equal(b[0], 1);
  assert.deepEqual(b.subarray(1, 33), FIELDS.device_pubkey);
  assert.equal(b[33], 1);   // merchant
  assert.equal(b[34], 1);   // active
  assert.deepEqual(b.subarray(35, 67), Buffer.from(getAddressEncoder().encode(FIELDS.attestation)));
  assert.deepEqual(b.subarray(67, 99), FIELDS.solana_ata);
  assert.deepEqual(b.subarray(99, 131), Buffer.alloc(32));   // no bank_ref_hash
  assert.equal(b.readUInt32LE(131), 1800000000);
  assert.equal(b.readUInt32LE(135), 1790000000);
  assert.equal(b[139], 12);
  assert.equal(b.subarray(140).toString('ascii'), 'MHacks Merch');

  const r = compactRecord({ ...FIELDS, attestation: null, kind: 'relay', status: 'revoked', solana_ata: null, display_name: 'x'.repeat(32) });
  assert.equal(r.length + 64, 236);   // the §9.3 maximum with sig
  assert.equal(r[33], 3);
  assert.equal(r[34], 2);
  assert.deepEqual(r.subarray(35, 99), Buffer.alloc(64));
});

test('buildSignedRecord signs compact with registry-c: and full with registry:', async () => {
  const s = await issuer();
  for (const [format, prefix] of [['full', 'registry:'], ['compact', 'registry-c:']]) {
    const { record, sig } = await buildSignedRecord(s, FIELDS, format);
    const bytes = Buffer.from(record, 'base64'), signature = Buffer.from(sig, 'base64');
    assert.equal(signature.length, 64);
    assert.ok(ed25519Ok(s, Buffer.concat([Buffer.from(prefix), bytes]), signature), format);
  }
  await assert.rejects(buildSignedRecord(s, FIELDS, 'xml'));
});

test('getSignedRecord: 404 for an unknown key, 200 with a fresh signature otherwise', async () => {
  const s = await createKeyPairSignerFromPrivateKeyBytes(crypto.getRandomValues(new Uint8Array(32)));
  assert.deepEqual(await getSignedRecord(s, 'unknown', 'full', async () => null), { status: 404 });
  const res = await getSignedRecord(s, 'known', 'compact', async () => ({ ...FIELDS, status: 'revoked' }));
  assert.equal(res.status, 200);
  assert.equal(Buffer.from(res.body.record, 'base64')[34], 2);
});
