// R6 fuzz set, laptop half. Run from the repo root (the .env gives HACK_MINT / HACK_DECIMALS):
//   node --env-file-if-exists=dashboard/.env harness/r6_fuzz.mjs [--badge 1 | --pubkey <base58>] [--mint <addr>] [--only begin_solana,sol-012,...] [--port 8790]
//   node harness/r6_fuzz.mjs --list            print the fuzz set (--out <dir> puts the report somewhere else)
//   node harness/r6_fuzz.mjs --export <file>   write the set (with fixed TEST payer and mint) for A's firmware tests
//
// R6 message fuzz set (docs/specs/P1-r-test-harness.md R6), served through the R3 path: the same
// GET /badge/pending?badge=<pubkey> / POST /badge/outcome listener shape. The badge app
// harness/apps/r6-fuzz/ fetches one case at a time, calls the named wallet function (begin_solana,
// sign_request, sign_proof, begin_bank) under pcall and reports what came back. Pass = every fuzz
// input refused, no signature, no crash or watchdog reset, and each function's control accepted (a
// control that is refused makes that function's results inconclusive: the decoder was never reached).
//
// Crashes: the app writes the case id to NVS before each call and clears it after. A relaunch that
// finds it reports `crash` for that case. Each request carries the badge's uptime; uptime going
// backwards means the badge itself reset (watchdog or panic) rather than only the app dying.
//
// The case set and the reference decoders it is checked against live in harness/fuzz_cases.mjs.
import http from 'node:http';
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { parseArgs } from 'node:util';
import { networkInterfaces } from 'node:os';
// The dashboard's config (badges.json, .env values) and R5's signature check are imported by path;
// their own dependencies resolve from dashboard/node_modules, so run `npm install` in dashboard/ once.
import { env, ROOT, loadBadges } from '../dashboard/server/src/config.js';
import { sigOk } from '../dashboard/server/src/verify.js';
import { buildCases, exportCase, addressBytes, isAddress, TEST_PAYER, TEST_MINT } from './fuzz_cases.mjs';

const HANG_WARN_MS = 60_000;   // APPROVAL_TIMEOUT_S (45 s) plus slack
const SIGNED_PREFIX = { begin_solana: '', begin_bank: 'bank-auth:', sign_request: 'pay-req:', sign_proof: 'pay-proof:' };

const die = msg => { console.error(`r6: ${msg}`); process.exit(1); };
const { values: arg } = parseArgs({ options: {
  badge: { type: 'string', default: '1' }, pubkey: { type: 'string' },
  mint: { type: 'string' }, decimals: { type: 'string' },
  only: { type: 'string' }, 'no-controls': { type: 'boolean', default: false },
  host: { type: 'string', default: '0.0.0.0' }, port: { type: 'string', default: '8790' },
  list: { type: 'boolean', default: false }, export: { type: 'string' }, out: { type: 'string' },
} });

// ── export for A: fixed test keys, so the file is stable and matches fuzz_cases.test.mjs ──
if (arg.export) {
  const cases = buildCases({ payer: TEST_PAYER, mint: TEST_MINT, decimals: 2 }).map(exportCase);
  const file = resolve(process.cwd(), arg.export);
  writeFileSync(file, `${JSON.stringify({
    about: 'R6 fuzz set (docs/specs/P1-r-test-harness.md R6). Generated by `node harness/r6_fuzz.mjs --export harness/fuzz-vectors.json`; do not edit. '
      + 'Built for the TEST payer and mint below: a firmware host test pins those, then expects every `refuse` case to be refused '
      + '(begin_* with reason "undecodable") and every control accepted. args: t=b bytes (hex), n number, nil, T empty table.',
    payer: TEST_PAYER, mint: TEST_MINT, decimals: 2, cases,
  }, null, 1)}\n`);
  console.log(`r6: wrote ${cases.length} cases to ${file}`);
  process.exit(0);
}

// ── who and what ────────────────────────────────────────────────────────────
const { badges } = loadBadges();
const payer = arg.pubkey ?? badges.find(b => String(b.id) === String(arg.badge) && b.pubkey)?.pubkey
  ?? die(`badge ${arg.badge} has no pubkey in badges.json (or pass --pubkey)`);
if (!isAddress(payer)) die(`not a pubkey: ${payer}`);
// The firmware pins the HACK mint: fuzzing against another one would make the controls fail, not the decoder.
const mint = arg.mint ?? (env.HACK_MINT || (arg.list ? TEST_MINT : die('HACK_MINT is not set: pass --mint <the mint pinned in the firmware>')));
const decimals = Number(arg.decimals ?? env.HACK_DECIMALS);
const payerBytes = addressBytes(payer);

let cases = buildCases({ payer, mint, decimals });
if (arg.only) {
  const keep = new Set(arg.only.split(',').map(s => s.trim()));
  const picked = cases.filter(c => keep.has(c.fn) || keep.has(c.group) || keep.has(c.id));
  const fns = new Set(picked.map(c => c.fn));   // a function's control always comes along
  cases = cases.filter(c => picked.includes(c) || (c.expect !== 'refuse' && fns.has(c.fn)));
}
if (arg['no-controls']) cases = cases.filter(c => c.expect === 'refuse');
// Controls first: the operator cancels their approval screens up front, then the rest runs unattended.
cases.sort((a, b) => (a.expect === 'refuse') - (b.expect === 'refuse'));
if (!cases.length) die('no cases selected');

if (arg.list) {
  for (const c of cases) {
    const size = c.args.filter(a => a.t === 'b').map(a => `${a.v.length} B`).join(', ');
    console.log(`${c.id}  ${c.fn.padEnd(12)} ${c.group.padEnd(12)} ${c.expect.padEnd(6)} ${c.basis.padEnd(6)} ${c.name}${size ? `  [${size}]` : ''}`);
  }
  process.exit(0);
}

// ── run state and report ─────────────────────────────────────────────────────
const stamp = new Date().toISOString().replace(/[-:]/g, '').replace(/\.\d+Z$/, 'Z');
const OUT = arg.out ? resolve(process.cwd(), arg.out) : resolve(ROOT, `../harness/results/${stamp}-r6`);
mkdirSync(OUT, { recursive: true });
const state = new Map(cases.map(c => [c.id, { served: 0, servedAt: 0, outcome: null, final: false, warned: false, notes: [] }]));
const events = [];
let lastUp = null;
const started = new Date().toISOString();

const signedBytes = c => Buffer.concat([Buffer.from(SIGNED_PREFIX[c.fn]), ...c.args.filter(a => a.t === 'b').map(a => a.v)]);

function judge(c) {
  const s = state.get(c.id), o = s.outcome;
  if (!o) return { verdict: 'not_run' };
  if (o.outcome === 'missing') return { verdict: 'skipped', why: `firmware has no wallet.${c.fn}` };
  if (o.outcome === 'crash') return { verdict: 'FAIL', why: o.reset ? 'badge reset during the call (watchdog or panic)' : 'app died during the call (Lua error or callback budget)' };
  const sigValid = o.outcome === 'signed' && sigOk(payerBytes, signedBytes(c), Buffer.from(o.sig ?? '', 'base64'));
  if (c.expect === 'refuse') {
    if (o.outcome === 'refused' || o.outcome === 'raised') {
      const notes = [];
      if (c.reason && o.outcome === 'raised') notes.push(`raised "${o.reason}" instead of returning nil, "${c.reason}"`);
      else if (c.reason && o.reason !== c.reason) notes.push(`reason "${o.reason}", spec says "${c.reason}"`);
      return { verdict: 'pass', why: notes.join('; ') };
    }
    if (o.outcome === 'screen') return { verdict: 'FAIL', why: `decoder accepted it: approval screen shown${s.final ? `, then ${o.after ?? 'closed'}` : ''}` };
    if (o.outcome === 'signed') return { verdict: 'FAIL', why: sigValid ? 'SIGNED (valid signature over the input)' : 'returned a 64-byte value' };
    return { verdict: 'FAIL', why: `unexpected return: ${o.reason ?? o.outcome}` };
  }
  // controls
  if (c.expect === 'screen' && o.outcome === 'screen') return { verdict: 'control_ok' };
  if (c.expect === 'signed' && sigValid) return { verdict: 'control_ok' };
  if (c.expect === 'signed' && o.outcome === 'signed') return { verdict: 'control_bad', why: 'signature does not verify against the badge key' };
  return { verdict: 'control_bad', why: `${o.outcome}${o.reason ? ` "${o.reason}"` : ''}: valid input did not reach the decoder's accept path` };
}

function summarize() {
  const fns = [...new Set(cases.map(c => c.fn))];
  return fns.map(fn => {
    const mine = cases.filter(c => c.fn === fn).map(c => ({ c, ...judge(c) }));
    const fuzz = mine.filter(x => x.c.expect === 'refuse');
    const count = v => fuzz.filter(x => x.verdict === v).length;
    const controls = mine.filter(x => x.c.expect !== 'refuse');
    const fails = fuzz.filter(x => x.verdict === 'FAIL');
    const pending = mine.filter(x => x.verdict === 'not_run').length;
    let verdict;
    if (mine.every(x => x.verdict === 'skipped')) verdict = 'skipped (not in firmware)';
    else if (pending) verdict = `incomplete (${pending} not run)`;
    else if (controls.some(x => x.verdict !== 'control_ok')) verdict = 'INCONCLUSIVE (control failed)';
    else if (fails.some(x => x.c.basis === 'spec')) verdict = 'FAIL';
    else if (fails.length) verdict = 'pass on spec rules; interpretation cases failed (agree with A)';
    else verdict = 'PASS';
    return { fn, verdict, total: fuzz.length, pass: count('pass'), fail: fails.length, skipped: count('skipped'),
      crashes: fuzz.filter(x => state.get(x.c.id).outcome?.outcome === 'crash').length, controls: controls.map(x => x.verdict) };
  });
}

// R6 is done only when A's Solana decoder ran and every function present passed on the spec rules.
function overall(summary) {
  const sol = summary.find(s => s.fn === 'begin_solana');
  const live = summary.filter(s => !s.verdict.startsWith('skipped'));
  if (live.some(s => s.verdict === 'FAIL')) return 'FAIL';
  if (live.some(s => s.verdict.startsWith('incomplete'))) return 'NOT DONE (run incomplete)';
  if (live.some(s => s.verdict.startsWith('INCONCLUSIVE'))) return 'INCONCLUSIVE (a control was refused: decoder never reached)';
  if (!sol || sol.verdict.startsWith('skipped')) return 'NOT DONE (firmware has no wallet.begin_solana yet)';
  return live.some(s => s.verdict.startsWith('pass on spec')) ? 'PASS on spec rules (interpretation cases to agree with A)' : 'PASS';
}

function writeReport() {
  const summary = summarize();
  const rows = cases.map(c => {
    const s = state.get(c.id), j = judge(c);
    return { ...exportCase(c), outcome: s.outcome, verdict: j.verdict, why: j.why ?? '', notes: s.notes };
  });
  writeFileSync(resolve(OUT, 'results.json'), `${JSON.stringify({ started, updated: new Date().toISOString(), payer, mint, decimals, r6: overall(summary), summary, events, cases: rows }, null, 1)}\n`);
  const esc = t => String(t ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
  const lines = [
    `# R6 fuzz run ${stamp}`, '',
    `Badge \`${payer}\` · mint \`${mint}\` (${decimals} decimals) · started ${started}`, '',
    `**R6: ${overall(summary)}**`, '',
    '| Function | Verdict | Fuzz cases | Refused | Failed | Crashes | Skipped | Controls |', '| --- | --- | --- | --- | --- | --- | --- | --- |',
    ...summary.map(s => `| \`${s.fn}\` | ${s.verdict} | ${s.total} | ${s.pass} | ${s.fail} | ${s.crashes} | ${s.skipped} | ${s.controls.join(', ')} |`),
    '',
  ];
  if (events.length) lines.push('## Badge resets', '', ...events.map(e => `- ${e.at}: uptime ${e.before} → ${e.after} ms${e.case ? ` while \`${e.case}\` was in flight` : ''}`), '');
  const bad = rows.filter(r => r.verdict === 'FAIL' || r.verdict === 'control_bad');
  if (bad.length) {
    lines.push('## Failures', '', '| Case | Function | Group | Input | Basis | Why |', '| --- | --- | --- | --- | --- | --- |',
      ...bad.map(r => `| ${r.id} | ${r.fn} | ${r.group} | ${esc(r.name)} | ${r.basis} | ${esc(r.why)} |`), '');
  }
  lines.push('## All cases', '', '| Case | Function | Group | Input | Expect | Outcome | Reason | Verdict | Note |', '| --- | --- | --- | --- | --- | --- | --- | --- | --- |',
    ...rows.map(r => `| ${r.id} | ${r.fn} | ${r.group} | ${esc(r.name)} | ${r.expect} | ${r.outcome?.outcome ?? ''} | ${esc(r.outcome?.reason)} | ${r.verdict} | ${esc([r.why, ...r.notes].filter(Boolean).join('; '))} |`), '');
  writeFileSync(resolve(OUT, 'table.md'), lines.join('\n'));
  return summary;
}

const nextCase = () => cases.find(c => !state.get(c.id).final);
const inFlight = () => cases.find(c => { const s = state.get(c.id); return s.served && !s.final; });

function wire(c) {
  const out = { id: c.id, fn: c.fn, expect: c.expect, name: c.name.replace(/["\\]/g, "'").slice(0, 48), index: cases.indexOf(c) + 1, total: cases.length, n: c.args.length };
  c.args.forEach((a, i) => {
    out[`t${i + 1}`] = a.t;
    out[`a${i + 1}`] = a.t === 'b' ? a.v.toString('base64') : a.t === 'n' ? String(a.v) : '';
  });
  if (c.args[0]?.t === 'b') out.messageBase64 = out.a1;   // R3 shape
  return out;
}

function noteUptime(up) {
  if (!Number.isFinite(up)) return;
  if (lastUp !== null && up + 1000 < lastUp) {
    const c = inFlight();
    events.push({ at: new Date().toISOString(), before: lastUp, after: up, case: c?.id ?? null });
    console.log(`r6: BADGE RESET (uptime ${lastUp} -> ${up} ms)${c ? ` with ${c.id} in flight` : ''}`);
    if (c) state.get(c.id).notes.push('badge reset while in flight');
  }
  lastUp = up;
}

function record(body) {
  const c = cases.find(x => x.id === body.id);
  if (!c) return false;
  const s = state.get(c.id);
  const outcome = String(body.outcome ?? '');
  const reason = body.reason == null ? null : String(body.reason).slice(0, 200);
  if (outcome === 'screen') {
    s.outcome = { outcome: 'screen', reason: null, ms: body.ms };
    console.log(c.expect === 'screen'
      ? `r6: ${c.id} control reached the approval screen as expected. Press CANCEL on the badge.`
      : `r6: !!! ${c.id} (${c.name}) REACHED THE APPROVAL SCREEN. Press CANCEL on the badge (never SELECT).`);
  } else if (s.outcome?.outcome === 'screen' && outcome !== 'crash') {
    // the approval finished: keep "screen" as the verdict-relevant outcome, record how it ended
    s.outcome = { ...s.outcome, after: outcome === 'signed' ? 'signed' : reason, sig: body.sig };
    if (outcome === 'signed' && c.expect === 'refuse') s.outcome = { outcome: 'signed', sig: body.sig, reason: 'approved on screen' };
    s.final = true;
  } else {
    s.outcome = { outcome, reason, sig: body.sig, ms: body.ms, reset: outcome === 'crash' && events.some(e => e.case === c.id) };
    s.final = true;
  }
  const j = judge(c);
  if (s.final) console.log(`r6: ${c.id} ${c.fn} ${c.name.slice(0, 50).padEnd(50)} -> ${s.outcome.outcome}${s.outcome.reason ? ` "${s.outcome.reason}"` : ''}  ${j.verdict}${j.why ? ` (${j.why})` : ''}`);
  return true;
}

function finishIfDone() {
  if (nextCase()) return;
  const summary = writeReport();
  console.log(`\nr6: done. R6: ${overall(summary)}`);
  for (const s of summary) console.log(`  ${s.fn.padEnd(13)} ${s.verdict}  (${s.pass}/${s.total} refused, ${s.fail} failed, ${s.crashes} crashes)`);
  console.log(`r6: report in ${OUT}/table.md`);
}

// ── listener (R3 shape) ──────────────────────────────────────────────────────
const json = (res, code, body) => { res.writeHead(code, { 'content-type': 'application/json' }); res.end(body === undefined ? '' : JSON.stringify(body)); };
const readBody = req => new Promise((ok, fail) => {
  let data = '';
  req.on('data', c => { data += c; if (data.length > 4096) { req.destroy(); fail(new Error('body too large')); } });
  req.on('end', () => { try { ok(JSON.parse(data)); } catch { fail(new Error('invalid JSON')); } });
});

const server = http.createServer(async (req, res) => {
  const url = URL.parse(req.url, 'http://badge');
  try {
    if (req.method === 'GET' && url?.pathname === '/badge/pending') {
      if (url.searchParams.get('badge') !== payer) return json(res, 204);
      noteUptime(Number(url.searchParams.get('up')));
      const c = nextCase();
      if (!c) return json(res, 204);
      const s = state.get(c.id);
      s.served++; s.servedAt = Date.now(); s.warned = false;
      if (s.served > 1) s.notes.push(`served ${s.served}x`);
      return json(res, 200, wire(c));
    }
    if (req.method === 'POST' && url?.pathname === '/badge/outcome') {
      const body = await readBody(req);
      noteUptime(Number(body.up));
      if (!record(body)) return json(res, 404, { ok: false, reason: 'unknown_case' });
      writeReport();
      json(res, 200, { ok: true });
      finishIfDone();
      return;
    }
    json(res, 404, { ok: false, reason: 'not_found' });
  } catch (err) {
    console.error(`r6: ${err.message}`);
    json(res, 500, { ok: false, reason: 'error' });
  }
});

setInterval(() => {
  const c = inFlight();
  if (!c) return;
  const s = state.get(c.id);
  if (!s.warned && Date.now() - s.servedAt > HANG_WARN_MS) {
    s.warned = true;
    console.log(`r6: no outcome for ${c.id} after ${HANG_WARN_MS / 1000} s. Badge hung or reset? Relaunch R6 on the badge; it reports a crash for this case.`);
  }
}, 5000).unref();

process.on('SIGINT', () => {
  const summary = writeReport();
  console.log(`\nr6: stopped. R6: ${overall(summary)}`);
  for (const s of summary) console.log(`  ${s.fn.padEnd(13)} ${s.verdict}`);
  console.log(`r6: partial report in ${OUT}/table.md`);
  process.exit(0);
});

writeReport();
server.listen(Number(arg.port), arg.host, () => {
  const ip = Object.values(networkInterfaces()).flat().find(i => i.family === 'IPv4' && !i.internal)?.address ?? arg.host;
  const by = cases.reduce((m, c) => ({ ...m, [c.fn]: (m[c.fn] ?? 0) + 1 }), {});
  console.log(`r6: ${cases.length} cases (${Object.entries(by).map(([k, v]) => `${k} ${v}`).join(', ')}) for ${payer}, mint ${mint}`);
  console.log(`r6: badge polls http://${ip}:${arg.port}/badge/pending?badge=${payer}. Report: ${OUT}/table.md. Ctrl+C to stop.`);
});
