// Turns vectors.json into vectors.h for the host tests. It reads and writes next to itself, so it
// can be run from any directory: node vectors-to-h.mjs   (after vectors.mjs; see that file).
import { readFileSync, writeFileSync } from 'node:fs';
const v = JSON.parse(readFileSync(new URL('./vectors.json', import.meta.url), 'utf8'));
const arr = h => h.match(/../g).map(x => '0x' + x).join(',');
const alt = v.tx.legacy_alt_order, vk = v.vk;
let s = '/* generated by vectors.mjs + vectors-to-h.mjs from @solana/kit, sas-lib, @solana-program/token. Do not edit. */\n';
s += '#ifndef VK_HOST_VECTORS_H\n#define VK_HOST_VECTORS_H\n#include <stdint.h>\n';
s += '/* ---- Solana transfer messages (payer PAYER, 10.00 of MINT with 2 decimals, SRC -> DST) ---- */\n';
for (const [k, h] of Object.entries({
  PAYER: v.tx.payer_hex, SRC: v.tx.source_ata3_hex, DST: v.tx.dest_ata1_hex, DST_OWNER: v.tx.dest_owner_hex,
  MINT: v.tx.mint_hex, BH: v.tx.blockhash_hex, LEGACY: v.tx.legacy_1000.messageHex,
  V0: v.tx.v0_1000.messageHex, CB_LEGACY: v.tx.legacy_compute_budget.messageHex,
  ALT_LEGACY: alt.messageHex, ALT_OWNER: alt.owner_hex, ALT_MINT: alt.mint_hex, ALT_SRC: alt.source_hex, ALT_DST: alt.dest_hex }))
  s += `static const uint8_t V_${k}[] = {${arr(h)}};\n`;
s += `static const char B58_PAYER[] = "${v.tx.payer}";\n`;
s += '/* ---- Badge OS (vectors.json object "vk"). TEST KEYS ONLY. ---- */\n';
for (const [k, h] of Object.entries({
  ISSUER_SEED: vk.issuer.seed_hex, ISSUER_PUB: vk.issuer.pubkey_hex,
  DEVICE_SEED: vk.device.seed_hex, DEVICE_PUB: vk.device.pubkey_hex,
  RECORD: vk.record.hex, RECORD_SIG: vk.record.sig_hex, REQ: vk.req.frame_hex,
  PROOF_NONCE: vk.proof.nonce_hex, PROOF_PAYER: vk.proof.payer_hex, PROOF_SIG: vk.proof.sig_hex,
  MEMO_LEGACY: vk.memo_tx.messageHex, MEMO_TEXT: Buffer.from(vk.memo_tx.memo, 'utf8').toString('hex') }))
  s += `static const uint8_t V_${k}[] = {${arr(h)}};\n`;
s += `static const char B58_ISSUER[] = "${vk.issuer.pubkey_b58}";\n`;
s += `static const char B58_DEVICE[] = "${vk.device.pubkey_b58}";\n`;
s += `#define V_RECORD_ISSUED_AT ${vk.record.issued_at}u\n`;
s += `#define V_RECORD_EXPIRY ${vk.record.expiry}u\n`;
s += `#define V_REQ_SIGNED_LEN ${vk.req.signed_len}\n`;
s += `#define V_REQ_EXPIRY ${vk.req.expiry}u\n`;
s += `#define V_REQ_AMOUNT ${vk.req.amount}u\n`;
s += '#endif\n';
writeFileSync(new URL('./vectors.h', import.meta.url), s);
